import { getWalletUser } from '@/lib/wallet-auth';
import { db,identity,sameOrigin,errorResponse,StoreError,type OrderRow } from '@/lib/store-server';
import { feeWallet,invoiceHash } from '@/lib/split-checkout';
import { sellerAmount } from '@/lib/direct-proof';
import { verifyTransfer,failedTransfer } from '@/lib/direct-checkout';
export const dynamic='force-dynamic';
type Payout={id:string;seller:string;recipient:string;sender:string;asset:string;chain_id:number;token:string;amount_raw:string;reference:string;created:string;status:string;tx_hash:string|null;paid_at:string|null;last_check:number};
export async function GET(){try{const u=await getWalletUser();if(!u)throw new StoreError('Підключіть гаманець.',401);const owner=u.address.toLowerCase()===feeWallet();const liabilities=await db().prepare("SELECT o.*,i.payout_id FROM orders o LEFT JOIN payout_items i ON i.order_id=o.id WHERE o.status='paid' AND o.payment_version=3"+(owner?'':' AND o.seller=?')+' ORDER BY o.payout_due').bind(...(owner?[]:[u.userId])).all<OrderRow & {payout_id:string|null}>();const payouts=await db().prepare('SELECT * FROM payouts'+(owner?'':' WHERE seller=?')+' ORDER BY created DESC').bind(...(owner?[]:[u.userId])).all<Payout>();return Response.json({owner,liabilities:liabilities.results.map(o=>({orderId:o.id,name:o.name,recipient:o.wallet,asset:o.asset,chainId:o.chain_id,amountRaw:sellerAmount(o.amount_raw!),due:o.payout_due,payoutId:o.payout_id})),payouts:payouts.results.map(view)},{headers:{'Cache-Control':'no-store'}});}catch(e){return errorResponse(e);}}
function view(p:Payout){return {id:p.id,recipient:p.recipient,sender:p.sender,asset:p.asset,chainId:p.chain_id,token:p.token,amountRaw:p.amount_raw,reference:p.reference,created:p.created,status:p.status,txHash:p.tx_hash,paidAt:p.paid_at};}
export async function POST(req:Request){try{sameOrigin(req);const u=await identity(),platform=feeWallet();if(!platform||u.address.toLowerCase()!==platform)throw new StoreError('Виплати доступні лише власнику платформи.',403);const f=await req.formData(),action=String(f.get('action'));
 if(action==='prepare'){const rows=await db().prepare("SELECT o.* FROM orders o LEFT JOIN payout_items i ON i.order_id=o.id WHERE o.status='paid' AND o.payment_version=3 AND o.payout_due<=? AND i.order_id IS NULL ORDER BY o.created LIMIT 250").bind(new Date().toISOString()).all<OrderRow>();const groups=new Map<string,OrderRow[]>();for(const o of rows.results){const key=[o.seller,o.wallet,o.asset,o.chain_id].join(':');groups.set(key,[...(groups.get(key)||[]),o]);}const statements:D1PreparedStatement[]=[];for(const group of groups.values()){const o=group[0],id=crypto.randomUUID(),amount=group.reduce((sum,row)=>sum+BigInt(sellerAmount(row.amount_raw!)),BigInt(0)).toString();statements.push(db().prepare("INSERT INTO payouts (id,seller,recipient,sender,asset,chain_id,token,amount_raw,reference,created,status) VALUES (?,?,?,?,?,?,?,?,?,?,'pending')").bind(id,o.seller,o.wallet,platform,o.asset,o.chain_id,o.token,amount,invoiceHash(id),new Date().toISOString()));if(o.wallet===platform)statements.push(db().prepare("UPDATE payouts SET status='retained',paid_at=? WHERE id=?").bind(new Date().toISOString(),id));for(const row of group)statements.push(db().prepare('INSERT INTO payout_items (order_id,payout_id) VALUES (?,?)').bind(row.id,id));}if(statements.length)await db().batch(statements);return Response.json({ok:true,count:groups.size});}
 const id=String(f.get('id')||''),p=await db().prepare('SELECT * FROM payouts WHERE id=?').bind(id).first<Payout>();if(!p)throw new StoreError('Виплату не знайдено.',404);if(['paid','retained'].includes(p.status))return Response.json({result:'paid',payout:view(p)});
 if(action==='begin'){const lock=await db().prepare("UPDATE payouts SET status='authorized' WHERE id=? AND status='pending' AND tx_hash IS NULL").bind(id).run();if(!lock.meta.changes)throw new StoreError('Переказ уже розпочато в іншій вкладці. Оновіть список.');return Response.json({ok:true});}
 if(action==='release'){await db().prepare("UPDATE payouts SET status='pending' WHERE id=? AND status='authorized' AND tx_hash IS NULL").bind(id).run();return Response.json({ok:true});}
 const hash=String(f.get('txHash')||'').toLowerCase();if(!/^0x[0-9a-f]{64}$/.test(hash))throw new StoreError('Вкажіть хеш транзакції.');if(p.sender!==platform)throw new StoreError('Гаманець платформи змінився. Потрібне узгодження старої виплати.');
 if(action==='reset'){if(!await failedTransfer(p.chain_id,hash,{sender:p.sender,recipient:p.recipient,token:p.token,amountRaw:p.amount_raw,reference:p.reference,created:p.created}))throw new StoreError('Повторний переказ дозволений лише після остаточного підтвердження невдалої транзакції.');await db().prepare("UPDATE payouts SET status='pending',tx_hash=NULL,last_check=0 WHERE id=? AND status IN ('pending','authorized')").bind(id).run();return Response.json({ok:true});}
 if(action==='submit'){if(p.tx_hash&&p.tx_hash!==hash)throw new StoreError('Для виплати вже збережено іншу транзакцію.');await db().prepare("UPDATE payouts SET tx_hash=? WHERE id=? AND status IN ('pending','authorized') AND (tx_hash IS NULL OR tx_hash=?)").bind(hash,id,hash).run();return Response.json({ok:true});}
 if(action==='verify'){const now=Date.now();const lock=await db().prepare("UPDATE payouts SET last_check=? WHERE id=? AND status IN ('pending','authorized') AND last_check<?").bind(now,id,now-10000).run();if(!lock.meta.changes)throw new StoreError('Зачекайте 10 секунд.',429);const result=await verifyTransfer(p.chain_id,hash,{sender:p.sender,recipient:p.recipient,token:p.token,amountRaw:p.amount_raw,created:p.created,reference:p.reference});if(result==='invalid')throw new StoreError('Переказ не відповідає виплаті. Перевірте адресу, суму та мережу.');if(result==='pending')return Response.json({result});await db().batch([db().prepare('INSERT INTO transfer_claims (key,reference) VALUES (?,?)').bind(p.chain_id+':'+hash,p.id),db().prepare("UPDATE payouts SET status='paid',tx_hash=?,paid_at=? WHERE id=? AND status IN ('pending','authorized')").bind(hash,new Date().toISOString(),id)]);return Response.json({result:'paid'});}
 throw new StoreError('Невідома дія.');
 }catch(e){if(e instanceof Error&&e.message.includes('UNIQUE constraint'))return errorResponse(new StoreError('Ці продажі або транзакцію вже оброблено. Оновіть список.'));return errorResponse(e);}}
