import { quoteUnits,contractCodeMatches,splitReceiptMatches } from './split-proof';
export { quoteUnits,contractCodeMatches,splitReceiptMatches } from './split-proof';
import { env } from 'cloudflare:workers';
import { encodeFunctionData, getAddress, keccak256, type Address } from 'viem';
import artifact from './checkout-artifact.json';
import { assets,networkById,type Asset } from './assets';
import { db,StoreError,type OrderRow } from './store-server';
import { rpc,type Receipt,type Block } from './payment';
export function feeWallet(){const address=env.PLATFORM_FEE_WALLET;if(!address||!/^0x[0-9a-fA-F]{40}$/.test(address)||/^0x0{40}$/.test(address))return null;return address.toLowerCase() as Address;}
export async function contractFor(chainId:number){const row=await db().prepare('SELECT value FROM platform_settings WHERE key=?').bind('checkout:'+chainId).first<{value:string}>();return row?.value as Address|undefined;}
export async function quote(cents:number,asset:Asset){if(asset.coin==='usd-coin')return BigInt(cents)*BigInt(10000);const r=await fetch('https://api.coingecko.com/api/v3/simple/price?ids='+encodeURIComponent('usd-coin,'+asset.coin)+'&vs_currencies=usd&include_last_updated_at=true',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new StoreError('Курс тимчасово недоступний. Оберіть USDC або спробуйте пізніше.',503);const data=await r.json() as Record<string,{usd:number;last_updated_at:number}>;for(const id of ['usd-coin',asset.coin]){const entry=data[id];if(!entry||!Number.isFinite(entry.usd)||entry.usd<=0||Date.now()/1000-entry.last_updated_at>300||entry.last_updated_at>Date.now()/1000+30)throw new StoreError('Актуальний курс недоступний. Оберіть USDC.',503);}return quoteUnits(cents,asset.decimals,BigInt(Math.round(data['usd-coin'].usd*1e8)),BigInt(Math.round(data[asset.coin].usd*1e8)));}
export async function platformView(){const wallet=feeWallet();const registered=await db().prepare("SELECT key,value FROM platform_settings WHERE key LIKE 'checkout:%'").all<{key:string;value:string}>();const contracts=Object.fromEntries(registered.results.map(r=>[r.key.slice(9),r.value]));return {feePercent:10,feeWallet:wallet,contracts,assets:assets.map(a=>({...a,network:networkById(a.chainId)!.name,enabled:!!wallet})),configurationNeeded:!wallet};}
export async function validateDeployment(chainId:number,address:Address){const network=networkById(chainId),platform=feeWallet();if(!network||!platform)throw new StoreError('Спочатку потрібно вказати гаманець комісії.');for(const endpoint of network.rpcs){const code=await rpc<string>(endpoint,'eth_getCode',[address,'latest']);if(!contractCodeMatches(code))throw new StoreError('Код контракту не відповідає перевіреному CodeSellerCheckout.');const platformData=encodeFunctionData({abi:artifact.abi,functionName:'platform'});const result=await rpc<string>(endpoint,'eth_call',[{to:address,data:platformData},'latest']);if(result.slice(-40).toLowerCase()!==platform.slice(2))throw new StoreError('Контракт має іншу адресу отримання комісії.');for(const asset of assets.filter(a=>a.chainId===chainId)){const data=encodeFunctionData({abi:artifact.abi,functionName:'allowed',args:[asset.token]});const allowed=await rpc<string>(endpoint,'eth_call',[{to:address,data},'latest']);if(BigInt(allowed)!==BigInt(1))throw new StoreError('Контракт не підтримує всі потрібні валюти мережі.');}}}
export async function verifySplitPayment(hash:string,o:OrderRow){const network=networkById(o.chain_id||0);if(!network||!o.contract||!o.fee_wallet||o.fee_wallet.toLowerCase()!==feeWallet())throw new StoreError('Рахунок має непідтримувану платіжну конфігурацію.');const checks=await Promise.all(network.rpcs.map(async endpoint=>{if(BigInt(await rpc<string>(endpoint,'eth_chainId',[]))!==BigInt(network.id))throw Error('Wrong RPC chain');const receipt=await rpc<Receipt|null>(endpoint,'eth_getTransactionReceipt',[hash]);if(!receipt)return {pending:true,valid:false,blockHash:''};const [block,finalized]=await Promise.all([rpc<Block|null>(endpoint,'eth_getBlockByNumber',[receipt.blockNumber,false]),rpc<Block|null>(endpoint,'eth_getBlockByNumber',['finalized',false])]);if(!block||!finalized)throw Error('Block unavailable');if(BigInt(finalized.number)<BigInt(receipt.blockNumber))return {pending:true,valid:false,blockHash:receipt.blockHash};return {pending:false,valid:splitReceiptMatches(receipt,block,finalized,o,hash),blockHash:receipt.blockHash};}));if(checks.some(c=>c.pending))return 'pending';return checks.every(c=>c.valid)&&checks[0].blockHash===checks[1].blockHash?'paid':'invalid';}
export function invoiceHash(id:string){return keccak256(new TextEncoder().encode(id));}
export function normalizeAddress(address:string){return getAddress(address) as Address;}
