import { decodeEventLog,type Hex } from 'viem';
import artifact from './checkout-artifact.json' with {type:'json'};
import type { OrderRow } from './store-server';
import type { Receipt,Block } from './payment';
export function quoteUnits(cents:number,decimals:number,baseUsdE8:bigint,assetUsdE8:bigint){if(baseUsdE8<=BigInt(0)||assetUsdE8<=BigInt(0))throw Error('Invalid rate');const numerator=BigInt(cents)*baseUsdE8*BigInt(10)**BigInt(decimals),denominator=BigInt(100)*assetUsdE8;return (numerator+denominator-BigInt(1))/denominator;}
export function contractCodeMatches(actual:string){const expected=artifact.runtime.slice(2).toLowerCase();let normalized=actual.slice(2).toLowerCase();if(normalized.length!==expected.length)return false;for(const refs of Object.values(artifact.immutableReferences))for(const ref of refs as {start:number;length:number}[]){normalized=normalized.slice(0,ref.start*2)+'0'.repeat(ref.length*2)+normalized.slice((ref.start+ref.length)*2);}return normalized===expected;}
export function splitReceiptMatches(receipt:Receipt,block:Block,finalized:Block,o:OrderRow,hash:string){if(receipt.status!=='0x1'||receipt.transactionHash.toLowerCase()!==hash.toLowerCase()||receipt.blockHash.toLowerCase()!==block.hash.toLowerCase()||BigInt(receipt.blockNumber)!==BigInt(block.number)||BigInt(finalized.number)<BigInt(block.number)||Number(BigInt(block.timestamp))*1000<Math.floor(Date.parse(o.created)/1000)*1000||Number(BigInt(block.timestamp))>(o.deadline||0))return false;
 const expectedAmount=BigInt(o.amount_raw||0),buyer=o.buyer.replace(/^wallet:/,'').toLowerCase();
 return receipt.logs.some(log=>{if(log.removed||log.address.toLowerCase()!==o.contract?.toLowerCase())return false;try{const event=decodeEventLog({abi:artifact.abi,data:log.data as Hex,topics:log.topics as [Hex,...Hex[]]}) as unknown as {eventName:string;args:{orderId:string;buyer:string;seller:string;token:string;amount:bigint;sellerAmount:bigint;feeAmount:bigint;deadline:bigint}};const a=event.args;return event.eventName==='Purchase'&&a.orderId.toLowerCase()===o.order_hash?.toLowerCase()&&a.buyer.toLowerCase()===buyer&&a.seller.toLowerCase()===o.wallet.toLowerCase()&&a.token.toLowerCase()===o.token?.toLowerCase()&&a.amount===expectedAmount&&a.feeAmount===expectedAmount/BigInt(10)&&a.sellerAmount===expectedAmount-a.feeAmount&&a.deadline===BigInt(o.deadline||0);}catch{return false;}});
}
