import { createPublicClient,createWalletClient,custom,http,erc20Abi,zeroAddress,type Address,type Hex,type EIP1193Provider } from 'viem';
import { mainnet,bsc,polygon } from 'viem/chains';
import { networkById } from './assets';
export type InjectedProvider=EIP1193Provider & {on?:(event:string,listener:(accounts:string[])=>void)=>void;removeListener?:(event:string,listener:(accounts:string[])=>void)=>void;providers?:InjectedProvider[]};
declare global{interface Window{ethereum?:InjectedProvider;}}
export function injected(){const provider=window.ethereum;if(!provider)throw Error('Відкрийте цей сайт у браузері MetaMask або іншого EVM-гаманця.');return provider.providers?.find(p=>!!p)||provider;}
export function chainFor(id:number){return id===1?mainnet:id===56?bsc:polygon;}
export async function authApi(form:FormData){const r=await fetch('/api/auth',{method:'POST',body:form});const d=await r.json() as {error?:string;nonce:string;message:string;address:string};if(!r.ok)throw Error(d.error||'Не вдалося увійти.');return d;}
export async function connectWallet(){const provider=injected();const accounts=await provider.request({method:'eth_requestAccounts'});const address=accounts[0];if(!address)throw Error('Гаманець не надав адресу.');const challenge=new FormData();challenge.set('action','challenge');challenge.set('wallet',address);challenge.set('chainId',String(Number(await provider.request({method:'eth_chainId'}))));const c=await authApi(challenge);const signer=createWalletClient({account:address,transport:custom(provider)});const signature=await signer.signMessage({message:c.message});const login=new FormData();login.set('action','login');login.set('nonce',c.nonce);login.set('signature',signature);return (await authApi(login)).address;}
export async function disconnectWallet(){const form=new FormData();form.set('action','logout');await authApi(form);}
async function walletFor(id:number,expected:string){const provider=injected();const accounts=await provider.request({method:'eth_accounts'});if(accounts[0]?.toLowerCase()!==expected.toLowerCase())throw Error('Оберіть гаманець, через який ви увійшли.');const chain=chainFor(id);try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x'+id.toString(16)}]});}catch(e){if((e as {code?:number}).code!==4902)throw e;await provider.request({method:'wallet_addEthereumChain',params:[{chainId:'0x'+id.toString(16),chainName:chain.name,nativeCurrency:chain.nativeCurrency,rpcUrls:[networkById(id)!.rpcs[0]],blockExplorerUrls:[networkById(id)!.explorer]}]});await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x'+id.toString(16)}]});}const wallet=createWalletClient({chain,account:expected as Address,transport:custom(provider)});const publicClient=createPublicClient({chain,transport:http(networkById(id)!.rpcs[0])});return {wallet,publicClient};}
export type PayInvoice={chainId:number;feeWallet:string;orderHash:string;token:string;amountRaw:string;deadline:number};
export async function sendTransfer(chainId:number,sender:string,recipient:string,token:string,amountRaw:string,reference:string,onStatus:(s:string)=>void){const {wallet}=await walletFor(chainId,sender);onStatus('Підтвердіть переказ у гаманці.');return token.toLowerCase()===zeroAddress?wallet.sendTransaction({to:recipient as Address,value:BigInt(amountRaw),data:reference as Hex}):wallet.writeContract({address:token as Address,abi:erc20Abi,functionName:'transfer',args:[recipient as Address,BigInt(amountRaw)]});}
export async function payInvoice(o:PayInvoice,buyer:string,onStatus:(s:string)=>void){if(Date.now()/1000>=o.deadline)throw Error('Курс у рахунку застарів. Створіть новий рахунок.');return sendTransfer(o.chainId,buyer,o.feeWallet,o.token,o.amountRaw,o.orderHash,onStatus);}
