import { sqliteTable, text, integer, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const products=sqliteTable('products',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),description:text('description').notNull(),priceCents:integer('price_cents').notNull(),wallet:text('wallet').notNull(),category:text('category').notNull(),stack:text('stack').notNull(),version:text('version').notNull(),color:text('color').notNull(),fileKey:text('file_key').notNull(),fileName:text('file_name').notNull(),size:integer('size').notNull(),created:text('created').notNull(),archived:integer('archived').notNull().default(0)});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),buyer:text('buyer').notNull(),seller:text('seller').notNull(),productId:text('product_id').notNull(),name:text('name').notNull(),priceCents:integer('price_cents').notNull(),amountUnits:integer('amount_units').notNull(),wallet:text('wallet').notNull(),email:text('email').notNull(),fileKey:text('file_key').notNull(),fileName:text('file_name').notNull(),status:text('status').notNull().default('pending'),txHash:text('tx_hash'),licenseKey:text('license_key'),created:text('created').notNull(),paidAt:text('paid_at'),lastCheck:integer('last_check').notNull().default(0),paymentVersion:integer('payment_version').notNull().default(1),asset:text('asset'),chainId:integer('chain_id'),contract:text('contract'),token:text('token'),amountRaw:text('amount_raw'),orderHash:text('order_hash'),deadline:integer('deadline'),feeWallet:text('fee_wallet'),payoutDue:text('payout_due')},t=>[uniqueIndex('orders_chain_tx_unique').on(t.chainId,t.txHash)]);
export const authChallenges=sqliteTable('auth_challenges',{nonce:text('nonce').primaryKey(),wallet:text('wallet').notNull(),browserHash:text('browser_hash').notNull(),message:text('message').notNull(),expires:integer('expires').notNull(),used:integer('used').notNull().default(0)});
export const walletSessions=sqliteTable('wallet_sessions',{hash:text('hash').primaryKey(),wallet:text('wallet').notNull(),expires:integer('expires').notNull()});
export const walletLinks=sqliteTable('wallet_links',{legacyId:text('legacy_id').primaryKey(),wallet:text('wallet').notNull()});
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),n:integer('n').notNull(),expires:integer('expires').notNull()});
export const platformSettings=sqliteTable('platform_settings',{key:text('key').primaryKey(),value:text('value').notNull()});

export const payouts=sqliteTable('payouts',{id:text('id').primaryKey(),seller:text('seller').notNull(),recipient:text('recipient').notNull(),sender:text('sender').notNull(),asset:text('asset').notNull(),chainId:integer('chain_id').notNull(),token:text('token').notNull(),amountRaw:text('amount_raw').notNull(),reference:text('reference').notNull(),created:text('created').notNull(),status:text('status').notNull().default('pending'),txHash:text('tx_hash'),paidAt:text('paid_at'),lastCheck:integer('last_check').notNull().default(0)});
export const payoutItems=sqliteTable('payout_items',{orderId:text('order_id').primaryKey(),payoutId:text('payout_id').notNull()});
export const transferClaims=sqliteTable('transfer_claims',{key:text('key').primaryKey(),reference:text('reference').notNull()});
